### ISSUE TITLE
Randomized QMC: tests

### ISSUE THREAD

**Issue by mlsuh** [FriesischScott/UncertaintyQuantification.jl#144]
Currently, there are only tests for unrandomized qmc. Tests for randomized Sobol-, Halton- and Lattice Rule Sampling will need to be implemented.

**Comment by FriesischScott** [comment]
I checked and since there are sufficient tests in QMC.jl I think we can be very brief here and just check that under randomization the samples returned are different evry time or sth simple like that.

**Comment by FriesischScott** [comment]
@mlsuh Can you include this in #143 ?
