### ISSUE TITLE
Effect of transformations on QMC nets

### ISSUE THREAD

**Issue by FriesischScott** [FriesischScott/UncertaintyQuantification.jl#145]
To make sure everything were doing in regards to QMC is correct we need to do a bit of research and literature review. Mostly I'm interested in:

- What happens to the nets sampled using QMC methods under transformation from `[0,1]^d` to the marginal distributions of our random variables
  - As an example, in 2d, do samples of the Sobol' sequence retain their properties when transformed to standard normal random variables?
- What happens once dependencies such as copulas or muiltivariate normals are involved?
  - Does QMC even make sense in these cases? 
- Are all the transformations we are making valid, e.g. going from `[0,1]` to the marginals through the quantile function?

**Comment by FriesischScott** [comment]
Early research suggests, that the first and the last point are no issue and also the involvement of dependencies through copulas should be alright.

**Comment by FriesischScott** [comment]
@mlsuh As discussed on Monday I'd like you to see if you can find any sources in regard to using QMC for reliability analysis (estimating failure probabilities). At least for regular QMC I vaguely remember that there is an issue with estimating the variance. However, that might not be an issue for RQMC. In this case, we could throw a warning if users try to use unrandomized QMC methods for reliability analysis.

Another interesting point would be if RQMC performs better or worse for sensitivity analysis.

**Comment by mlsuh** [comment]
Regarding reliability anlysis, QMC outperforms MC when constructing low-discrepancy sequences.
However, as you suspected, a variance cannot be estimated. Randomization does fix this and allows for similar results as MC with fewer samples. 
This is shown in section 4 of this paper [Structural reliability analysis on the basis of small samples: An interval quasi-Monte Carlo method](https://www.sciencedirect.com/science/article/pii/S0888327012000787#s0040) by H. Zhang, H. Dai, M. Beer and W. Wang.

RQMC is also greatly applicable for sensitivity analysis as described in [Randomized quasi-Monte Carlo methods in global sensitivity analysis](https://www.sciencedirect.com/science/article/pii/S0951832021000818#d1e1649) by G. Ökten and Y. Liu.

**Comment by FriesischScott** [comment]
Thanks for the research @mlsuh. Ultimately some of this should go in the documentation. For now I'm closing this.
