### ISSUE TITLE
Include build scripts for c++ solvers in tests

### ISSUE THREAD

**Issue by AnderGray** [FriesischScott/UncertaintyQuantification.jl#150]
Package was failing when testing on my HPC machine, and getting a confusing error from Julia.

Eventually found it was the c++ external solvers used in some of the tests

i.e this one:
https://github.com/FriesischScott/UncertaintyQuantification.jl/blob/e62374b006d449b8e8b5a0a4aa0fc4a356d6da57/test/solvers/src/radius.c#L1

Perhaps it's worth including little build script for these c++ external solvers, and printing a custom error message in the case that these tests fail.

**Comment by FriesischScott** [comment]
Hey, thanks for reporting this. I think it would be good to potential move away from these compiled solvers. I see two potential solutions:

- Use a simple shell script `radius.sh` on `unix` machines and `radius.ps1` on windows machines.
- Use a standalone Julia script that can do this without needing any extra dependencies.

Any preferences?

**Comment by AnderGray** [comment]
I find the 100% Julia solution to be the cleanest, unless it defeats the purpose of the external model test?

**Comment by FriesischScott** [comment]
As long as I call it as a separate process it should't be a problem. I'll see what can be done.
