### ISSUE TITLE
Small bug in Opensees demo

### ISSUE THREAD

**Issue by AnderGray** [FriesischScott/UncertaintyQuantification.jl#154]
This line is pointing to the wrong directory
https://github.com/FriesischScott/UncertaintyQuantification.jl/blob/e2d4772c5fbd027014db7124dc9221bf30fce608/demo/reliability/supported-beam-opensees.jl#L12

points to `UncertaintyQuantification.jl/demo/reliability/demo/models/` 

and not `UncertaintyQuantification.jl/demo/models/`

**Comment by FriesischScott** [comment]
Thanks 👍 .

**Comment by FriesischScott** [comment]
Turns out that's not true. The paths are relative to the root of the project (which is supposed to be the `pwd`) and this is correct.
