### ISSUE TITLE
probabilityoffailure_impreciseprobabilities fails when simulations are all safe or all failure

### ISSUE THREAD

**Issue by andreaperin** [FriesischScott/UncertaintyQuantification.jl#161]
Evaluating pf with one or more imprecise inputs alwasys return an output pf that is a Interval. When all the simulations are in safe (or failed) state the check on the lower/upper bounds of the Interval struct fails. A solution could be returning a single value pf when the 2 buonds are equal.

**Comment by FriesischScott** [comment]
The imprecise code isn't even released yet. You should put this in the PR so we (you) can fix it before merging.
