### ISSUE TITLE
We're not using Modified (component-wise) MCMC in subset simulation

### ISSUE THREAD

**Issue by AnderGray** [FriesischScott/UncertaintyQuantification.jl#165]
In the docstrings of `SubSetSimulation`, we state that we're using the algorithm described in:

S.-K. Au and J. L. Beck. Estimation of Small Failure Probabilities in High Dimensions by Subset Simulation. [Probabilistic Engineering Mechanics 16, 263–277 (2001)](https://doi.org/10.1016/S0266-8920(01)00019-4)

A modified MCMC algorithm, which samples component wise, allowing for high dimensional problems.

Instead we've implemented standard MCMC, which struggles in high dimensions due to small densities of the proposal distribution, leading to small acceptance rates.

We should implement the modified version also, and change these docstrings.

**Comment by FriesischScott** [comment]
Btw, I think the *modified* refers to the extra rejection step. Component-wise Metropolis-Hastings (CMH) was already widely used before.
