### ISSUE TITLE
Drop support for Julia 1.6 (lts)

### ISSUE THREAD

**Issue by FriesischScott** [FriesischScott/UncertaintyQuantification.jl#170]
I think we can safely abandon support for the `lts` version of Julia (1.6 currently) and focus only on the current release.  Some of our dependencies  already stopped supporting 1.6 in their latest release (QuasiMonteCarlo.jl for example).  This will ultimately force us to drop support as well.  

I don't see potential users of our package requiring the extra stability of the `lts` version and  see no downside  to supporting only the latest release starting now.

It will also allow us to use  new features of Julia as soon as they are released.

**Comment by AnderGray** [comment]
Principally no problem with dropping support for long-term supported Julia versions. 

Only issue I can think of is that on HPC machines, it's often the `lts` versions that are installed by the admins. Would mean that users may have to install Julia themselves. But this is however simple to do.

**Comment by FriesischScott** [comment]
Closed by #174 .
