### ISSUE TITLE
Incorrect usage of probability_of_failure in \demo\reliability\supported-beam-opensees.jl line 42

### ISSUE THREAD

**Issue by mbvoyager** [FriesischScott/UncertaintyQuantification.jl#208]
In \demo\reliability\supported-beam-opensees.jl line 42, I found:

`pf, samples = probability_of_failure(ext, df -> 0.35 .- df.disp, E, MonteCarlo(1000))`

which should be:

`pf, mc_std, samples = probability_of_failure(ext, df -> 0.35 .- df.disp, E, MonteCarlo(1000))`

Seems like there were some changes in the past, so possibly this output assignment is also wrong at a different position. I haven't found other wrong usages so far though.

**Comment by FriesischScott** [comment]
This example needs to be rewritte in `Literate.jl` as a part of a larger rewrite of the demos.

**Comment by FriesischScott** [comment]
This will be done as part of #195
