### ISSUE TITLE
Pretty docs using Documenter Vitepress

### ISSUE THREAD

**Issue by AnderGray** [FriesischScott/UncertaintyQuantification.jl#221]
It's quite easy to host the docs using JavaScript / node.js with [DocumenterVitepress.jl](https://github.com/LuxDL/DocumenterVitepress.jl).

You pretty much just need to change the format in `docs/make.jl` 
https://github.com/FriesischScott/UncertaintyQuantification.jl/blob/41a89ea33bfdfa7325136057a09bc8ada5bed474/docs/make.jl#L17

To something like:

```julia
format=DocumenterVitepress.MarkdownVitepress(repo = "https://github.com/FriesischScott/UncertaintyQuantification.jl", devbranch = "master",
    build_vitepress = false,
    md_output_path = "."),
```

Has some quite nice results:
![Screenshot 2024-09-27 at 14 22 42](https://github.com/user-attachments/assets/c76d7ae6-2d83-4443-91cb-184fa7e2cf0c)

Not sure how this changes the plans to publish a pdf manual. It also makes the locally compiling the docs slightly more involved. I think we can add an option to the docs build, one for the standard way (locally), and one with vitepress.

**Comment by FriesischScott** [comment]
Building the pdf should be totally independent from this.

**Comment by FriesischScott** [comment]
Probably the easiest way to do this would be to add a second script `makeVite.jl` next to `make.jl`. We then extract the `pages` to another file which an be included in bot scripts so we don't have to maintain two lists.

**Comment by AnderGray** [comment]
This is a good idea. Otherwise I dunno if it's possible to have an optional compile of the docs like we do for the tests (i.e. for the HPC testing)

**Comment by FriesischScott** [comment]
looks like you can just pass arguments to a julia file directly.
