### ISSUE TITLE
Performance of generating SRM stochastic processes

### ISSUE THREAD

**Issue by mbvoyager** [FriesischScott/UncertaintyQuantification.jl#222]
I am trying to directly generate realizations of stochastic processes via spectral representation method, using the following code snipped:

```
ω = collect(0:0.6:150)

cp = CloughPenzien(ω, 0.1, 0.8π, 0.6, 8π, 0.6)

# Ground motion
gm = SpectralRepresentation(cp, collect(0:0.02:10), :gm)

gm_model = StochasticProcessModel(gm)

res = evaluate!(gm_model, sample(gm, 10^6))
```

In my opinion the performance is unsufficient, can someone please check and give me their opinion?

**Comment by FriesischScott** [comment]
`evaluate!` shouldn't return anything. And you really only need the `StochasticProcessModel` when you ant to use the  realizations down the line in another model and access them by `:gm`. if you just want realizations I'd do something like this:

```julia
samples = sample(gm, 10^6)

res = evaluate.(gm, eachrow(samples) 
```

We could think about adding an `evaluate` method that takes a `DataFrame` and returns a vector of time series like this.

**Comment by FriesischScott** [comment]
This shouldn't be an issue so I'm closing it.  As a workaround you can use `map` instead of broadcasting with `.`.
