### ISSUE TITLE
Choose a license

### ISSUE THREAD

**Issue by FriesischScott** [FriesischScott/UncertaintyQuantification.jl#5]
We need to choose a license for the project. GNU GPLv3 or MIT?

https://choosealicense.com/

**Comment by AnderGray** [comment]
What license does cossan have? If we're going to use any of it's code it might effect our license

**Comment by FriesischScott** [comment]
Cossan is GPLv3 but I don't think we will really be using any of its code. 

_The **GNU GPLv3** also lets people do almost anything they want with your project, except distributing closed source versions._

_The **MIT** License is short and to the point. It lets people do almost anything they want with your project, like making and distributing closed source versions._

**Comment by FriesischScott** [comment]
The difference comes down to allowing closed source or not. In that sense I think GNU GPLv3 would be nicer. @AnderGray Do you agree?
