### ISSUE TITLE
Delete ExternalModel output files

### ISSUE THREAD

**Issue by andreaperin** [FriesischScott/UncertaintyQuantification.jl#67]
```evaluate!``` function applied to ExternalModel (e.g. finite element models) could create a lot of unnecessary output files.
This files can easily saturate ROM when long simulations are performed.
A _cleanup_ flag should be implemented for deleting the whole folder containing the samples of one simulation, after the _extraction_ of all usefull values.

**Comment by FriesischScott** [comment]
Happy to accept a pull request :).
